travis:
  secure:
    BINSTAR_TOKEN: G740va3GZRPecQ0HGr2ovqoQBvukv9MLVYQpMASktSeIlILpnnr3zKs7rxbwF/ObYcynF6L6xYvj3etF+aSNOyRd1JJowBiyQfFPKEu8BDXVKNYzlYLgwKg930XvZGVoBXoiIQDhzOSwlGqNin5aSAfDS0SJrRdY6Qp1Har+xJ/If5a9ojTD02eZ+/+f+bwMs58LzXNfJ8X36+MqH1qel/YOLPZDZbjuiuJRZ3StySDBGnGOuZwOpHE3j7ijwi8E89HD9FF+K7SThF0BFLkcGV9JufrEjleyL9GBSqX8KJ/E/c0fik8tbMdBVUmLS+wwF7LjQBwpsBMnAuGGnFd5k93lLKlLL/HTVkyC+s3ikU022lkXm9YD6uzcCzq7/dkHVnIkqqXFDH3tEoyjO9Axz9IeqAapG8E1OGRdX6LdPEWdy/JI8vvbLrHRTJ2A4AgCHt9Bxlu092BSUmKMkeIkdUvKcITPplKwhQjkIYu8oKzzbSOCXMAmiT/X/DVHFJSlamRzT8wQL3udNUEbNhMO184HJmJbpyr6WGQl4u5JUbgFrHj9gnSaBVr73CTsGp7Ussq62K+O+iEi7dQzT54wXKclI9qXjGr71HAGCaoeEQay+0Zh1eopqYobEXQnq6i/ejN6/RCjh1gLjCt/QqcIinS/XUoQ/GhGGPQ33lhHBso=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
