travis:
  secure:
    BINSTAR_TOKEN: GIVJDFFx8LmHc/nFfXn1mhKOV2Q121cqENSoOGUg6KkyWsPkirsEM1RHYwVnIRBSWzoVe/EQezPpaRop489dvLx7eIYIjul+GL2cRzTNMl8VMApXF2qNFbg72mR5wxgCyV1LZPMfaOYSw7Lma8N1itBbIOjJLcoNtwtWUNkDsPhUtN8yQ9yUg9LPJIWr3wsf4SQwIvvzcJw56ReF03Umsx9uy6vcX68tZMChhnYe6KaZZO/RoSRdBvBV+XVADhF5UVCs6Ia7EYFlWrhWi6aG7RqPW34XqmnH0Ea3B5fWBL5KAE8kN7oqhVmZzXTXtdeUUf2zo1HBtWe73RdppUBTOUjp2EmI01BoQHFgWB99n0Fy82JASN5w9om38kn/uXNI4VHasYKbmnZDu2Hixvnqc1CtDRs1xVY4PuU4bcM/uZxVeQnQLj9x6BZf7qzWweNMYv2RSo3E2F+QT6gBcV12gzpdyHaSydKV7MrJP7jDTSD7WIl42h2B3S626kjuA2EhGDmKUtBKRr3XuuTKPC1r4mIb0stvqVn8GvYe4ipwRsS7vx+hFtY60CIXcYePgM41Q2OVKTo1nc9DIiVeivf/m4pe5FokM8rXtHZJTbmGZSTSlMTfsnMqkbV3cG5ASN0IV451Y48P9C6GpguDpk+EgY5J5MbMrO/CybIWKtSZzic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
